plugins {
    id "com.android.library"
    id "kotlin-android"
}

group 'com.example.imagegallerysaver'
version '1.0-SNAPSHOT'

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

android {
    namespace "com.example.imagegallerysaver"
    compileSdkVersion 30

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }
    defaultConfig {
        minSdkVersion 16
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}

dependencies {
    // 已移除kotlin-stdlib-jdk7依赖，因为它现在由kotlin-android插件自动提供
}
